### PR TITLE
feat(*): support arm64 building

### PR DESCRIPTION
**Pull request by liwandaniel**
构建命令

```bash
make docker DOCKER_IMAGE_TAG=v0.0.1 ARCH=arm64
```

构建镜像

```
cargo.caicloud.xyz/arm64v8/mongodb-exporter:v0.0.1
```

arm64 运行测试
image

/cc @bbbmj @supereagle

### CODE REVIEW

**Review by supereagle — APPROVED** [review]
/lgtm

**Review by bbbmj — COMMENTED** [review]
/lgtm

**Comment by bbbmj** [comment]
manual merge as open source project.

**Pull request merged**
